# Generated by Django 3.2.8 on 2021-10-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Name', models.CharField(max_length=40)),
                ('Start_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=40)),
                ('Degree_Duration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Total_Sem', models.PositiveIntegerField()),
                ('Min_credit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=10, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacementCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(default='MediCaps University', max_length=40)),
                ('phone_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Location_Name', models.CharField(max_length=40)),
                ('Board', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=10, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.PositiveBigIntegerField()),
                ('Score10', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Score12', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('JeePercentile', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Aim', models.TextField(blank=True, null=True)),
                ('Objective', models.TextField(blank=True, null=True)),
                ('Mission', models.TextField(blank=True, null=True)),
                ('Vision', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('PlacementCell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.placementcell')),
                ('School10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SchoolX', to='api.school')),
                ('School12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SchoolXII', to='api.school')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=10, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_No', models.PositiveBigIntegerField()),
                ('placementCell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placementcell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageP2S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamps', models.DateTimeField()),
                ('Body', models.TextField()),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('receivers', models.ManyToManyField(to='api.Student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placementcell')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='Degree',
            field=models.ManyToManyField(to='api.Degree'),
        ),
    ]
