# Generated by Django 3.2.8 on 2021-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211016_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='Degree',
            new_name='Degree_Name',
        ),
        migrations.AddField(
            model_name='position',
            name='branch',
            field=models.ManyToManyField(to='api.Branch'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='Min_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='Total_Sem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
